version: '3'
services:
  web:
    build:
      context: .
      dockerfile: service-web.Dockerfile
    container_name: dockerlab
    ports:
    - "4000:80"
    volumes:
    - .:/var/www/html/docker
    depends_on: 
    - db
    - adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on: 
    - db
    ports:
      - 8080:8080
  db:
    build:
      context: .
      dockerfile: service-db.Dockerfile
    container_name: pg
    restart: always
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: