version: '3'
services:
  cli:
    build:
      context: .
      dockerfile: service-cli.Dockerfile
    container_name: trackercli
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
    - .:/usr/src/tracker
    environment:
    # especific environment variable to enable hot reloading
      - CHOKIDAR_USEPOLLING=true