version: '3'
services:
  web:
    build:
      context: .
      dockerfile: service-web.Dockerfile
    container_name: vuelab
    ports:
    - "4000:80"
    volumes:
    - .:/usr/local/apache2/htdocs/